---
- name: Complete Chapter 1 Lab
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name: Marketing
    org_label: Marketing
    org_desc: Marketing Department
    org_name_one: Operations
    org_locations:
      - Boston
  tasks:
    - name: Create Lab Organization
      redhat.satellite.organization:
        name: "{{ org_name }}"
        description: "{{ org_desc }}"
        label: "{{ org_label }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"

    - name: Create Lab Locations
      redhat.satellite.location:
        name: "{{ item }}"
        organizations: "{{ org_name_one }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
      loop: "{{ org_locations }}"


    - name: Upload Manifest
      redhat.satellite.subscription_manifest:
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        manifest_path: "/home/student/manifest_marketing.zip"
        repository_url: http://cdn.lab.example.com 