---
- name: Complete Chapter 1 Lab
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name: Finance
    org_desc: Finance Department
    org_locations:
      - San Francisco
      - Tokyo
  tasks:

    - name: Create Lab Locations
      redhat.satellite.location:
        name: "{{ item }}"
        organizations: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
      loop: "{{ org_locations }}"


