---
- name: Complete Chapter 2 Lab
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name: Finance
    sat_repos:
      - rhel-9-for-x86_64-appstream-rpms 
      - rhel-9-for-x86_64-baseos-rpms 
    sat_client_repos:
      - satellite-client-6-for-rhel-9-x86_64-rpms
    cv_name: FinanceServerBase
    base_cv_repos: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9

  tasks:
    - name: Enable Repositories for RHEL Servers
      redhat.satellite.repository_set:
        label: "{{ item }}"
        organization: "{{ org_name }}"
        state: enabled
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - releasever: "9"
      loop: "{{ sat_repos }}"

    - name: Enable Repositories Satellite Clients 
      redhat.satellite.repository_set:
        label: "{{ item }}"
        organization: "{{ org_name }}"
        state: enabled
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        all_repositories: yes
      loop: "{{ sat_client_repos }}"

    - name: Create Sync Plan
      redhat.satellite.sync_plan:
        name: Sync Plan for Red Hat Products
        organization: "{{ org_name }}"
        enabled: true
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        sync_date: "2022-03-15 18:00:00 UTC"
        interval: daily
        products:
          - 'Red Hat Enterprise Linux for x86_64'

    - name: Sync Repositories
      redhat.satellite.repository_sync:
        organization: "{{ org_name }}"
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        product: Red Hat Enterprise Linux for x86_64


    - name: Create Build Lifecycle Environment
      redhat.satellite.lifecycle_environment:
        name: Build
        label: Build
        prior: Library
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"

    - name: Create Test Lifecycle Environment
      redhat.satellite.lifecycle_environment:
        name: Test
        label: Test
        prior: Build
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"

    - name: Create Deploy Lifecycle Environment
      redhat.satellite.lifecycle_environment:
        name: Deploy
        label: Deploy
        prior: Test
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"

    - name: Create the Base Content View
      redhat.satellite.content_view:
        name: Base
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - name: "{{ base_cv_repos }}"
            product: Red Hat Enterprise Linux for x86_64

    - name: Publish the Base Content View - Not Idempotent
      redhat.satellite.content_view_version:
        content_view: Base
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        lifecycle_environments:
          - Library
          - Build
