---
- name: Complete Chapter 2 GE - Publish and Promote Content Views
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name_one: Operations
    org_name_two: Marketing
    cv_name: OperationsServerBase
    base_cv_repos: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9



  tasks:
  
    - name: Create the Base Content View
      redhat.satellite.content_view:
        name: "{{ cv_name }}"
        organization: "{{ org_name_one }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - name: "{{ base_cv_repos }}"
            product: Red Hat Enterprise Linux for x86_64


    - name: Publish the Base Content View - Not Idempotent
      redhat.satellite.content_view_version:
        content_view: "{{ cv_name }}"
        organization: "{{ org_name_one }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        description: Initial base repositories
        lifecycle_environments:
          - Library
          - Development
          - QA

    - name: Update the Base Content View
      redhat.satellite.content_view:
        name: "{{ cv_name }}"
        organization: "{{ org_name_one }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
            product: Red Hat Enterprise Linux for x86_64
          - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
            product: Red Hat Enterprise Linux for x86_64
          - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9 
            product: Red Hat Enterprise Linux for x86_64           

    - name: Publish the Base Content View - Not Idempotent
      redhat.satellite.content_view_version:
        content_view: "{{ cv_name }}"
        organization: "{{ org_name_one }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        description: Initial base repositories
        lifecycle_environments:
          - Library
          - Development
