---
- name: Complete Chapter 4 Lab - Deploy Software to Hosts
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name: Finance
    sat_repos:
      - Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
      - Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
      - Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
    activation_key: FinanceServers
    lifecycle_env: Build
    content_view: FinanceServerBase
    subscriptions:
      - name: "Red Hat Enterprise Linux Server, Standard (Physical or Virtual Nodes)"
      - name: "Red Hat Satellite Infrastructure Subscription"
    organization: "{{ org_name }}"
    repositories:
      - satellite-client-6-for-rhel-9-x86_64-rpms
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
    base_cv_repos: 
      - Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
      - Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
      - Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
## Updated Base Repos

  tasks:

    - name: Update the Base Content View
      redhat.satellite.content_view:
        name: FinanceServerBase
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
            product: Red Hat Enterprise Linux for x86_64
          - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
            product: Red Hat Enterprise Linux for x86_64
          - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
            product: Red Hat Enterprise Linux for x86_64

    - name: Publish the Base Content View - Not Idempotent
      redhat.satellite.content_view_version:
        content_view: FinanceServerBase
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        lifecycle_environments:
          - Library
          - Build

    - name: Enable Repository RHEL 9 HA
      redhat.satellite.repository_set:
        label: rhel-9-for-x86_64-highavailability-rpms
        organization: "{{ org_name }}"
        state: enabled
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - releasever: "9"

    - name: Sync Repositories to get HA
      redhat.satellite.repository_sync:
        organization: "{{ org_name }}"
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        product: Red Hat Enterprise Linux High Availability for x86_64 

    - name: Create FinBaseHA Content View
      redhat.satellite.content_view:
        name: BaseHAComposite
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        repositories:
          - name: Red Hat Enterprise Linux 9 for x86_64 - High Availability RPMs 9
            product: Red Hat Enterprise Linux High Availability for x86_64 

      redhat.satellite.content_view_version:
        content_view: BaseHAComposite
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        lifecycle_environments:
          - Library
          - Build

    - name: Create Composite Content View
      redhat.satellite.content_view:
        name: BaseHAComposite
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"


- name: Complete Chapter 4 Lab -  Register Host ServerB To Satellite
  hosts: serverb.lab.example.com
  vars_files:
    - sat_vars.yml
  vars:
    activation_key: FinanceKey
    org_name: Finance


  tasks:

    - name: Unregister Server
      redhat_subscription:
        state: absent

    - name: Prepare System for Satellite Registration - Get Cert
      get_url:
        url: "{{ sat_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
        dest: /tmp/katello-latest.rpm
        validate_certs: no

    - name: Install Katello rpm
      yum:
        name: /tmp/katello-latest.rpm
        state: latest
        disable_gpg_check: yes

    - name: Register with Activation key
      redhat_subscription:
        state: present
        activationkey: "{{ activation_key }}"
        org_id: "{{ org_name }}"
      when: activation_key is defined
