---
- name: CH8 GE - Lab Network Provisioning Configure
  hosts: capsule
  vars_files: sat_vars.yml

  tasks: 

    - name: Setup Capsule Provisioing Components
      shell: |
        satellite-installer --scenario capsule \
        --foreman-proxy-dns true \
        --foreman-proxy-dns-interface eth0 \
        --foreman-proxy-dns-forwarders 172.25.250.254 \
        --foreman-proxy-dns-zone boston.lab.example.com \
        --foreman-proxy-dns-reverse 250.25.172.in-addr.arpa \
        --foreman-proxy-dhcp true \
        --foreman-proxy-dhcp-interface eth0 \
        --foreman-proxy-dhcp-range "172.25.250.50 172.25.250.100" \
        --foreman-proxy-dhcp-nameservers 172.25.250.220 \
        --foreman-proxy-dhcp-gateway 172.25.250.254 \
        --foreman-proxy-tftp true

    - name: Setup Capsule Ansible Components
      shell: |
        satellite-installer --scenario capsule \
        --enable-foreman-proxy-plugin-ansible
