---
- name: Fix Satellite Yum Repos
  hosts: satellite.lab.example.com

  tasks:

    - name: Replace /etc/yum.repos.d/rhs_dvd.repo file on Satellite
      ansible.builtin.copy:
        src: Files/rhs_dvd.repo
        dest: /etc/yum.repos.d/rhs_dvd.repo
